### ISSUE TITLE
Server error 500 when Exporting filtered list

### ISSUE THREAD

**Issue by wyrzykow** [wyrzykow/bhtom#156]
e.g. https://bh-tom.astrolabs.pl/targets/export/?type=&name=Gaia&key=&value=&cone_search=&targetlist__name=&ra_min=&ra_max=&dec_min=&dec_max=0&target_cone_search=&gaia_alert_name=&calib_server_name=&ztf_alert_name=&aavso_name=&gaiadr2_id=&TNS_ID=&classification=&jdlastobs_min=&jdlastobs_max=&maglast_min=&maglast_max=16&priority_min=5&priority_max=&dicovery_date_after=&dicovery_date_before=&cadence_min=&cadence_max=&Sun_separation_min=60&Sun_separation_max=&dont_update_me=unknown

**Comment by tmac-rvx** [comment]
2023-03-05 12:46:00,376 django.request ERROR    Internal Server Error: /targets/export/
Traceback (most recent call last):
  File "/home/bhtom/bhtom/bhtom-env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/bhtom/bhtom/bhtom-env/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/bhtom/bhtom/bhtom-env/lib/python3.6/site-packages/django/core/handlers/base.py", line 155, in process_exception_by_middleware
    response = middleware_method(request, exception)
  File "/home/bhtom/bhtom/bhtom-env/lib/python3.6/site-packages/sentry_sdk/integrations/django/middleware.py", line 110, in sentry_wrapped_method
    return old_method(*args, **kwargs)
  File "/home/bhtom/bhtom/bhtom/middleware/external_service_middleware.py", line 37, in process_exception
    raise exception
  File "/home/bhtom/bhtom/bhtom-env/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/bhtom/bhtom/bhtom-env/lib/python3.6/site-packages/sentry_sdk/integrations/django/views.py", line 67, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "/home/bhtom/bhtom/bhtom-env/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/bhtom/bhtom/bhtom-env/lib/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/bhtom/bhtom/bhtom-env/lib/python3.6/site-packages/django_filters/views.py", line 81, in get
    self.object_list = self.filterset.qs
  File "/home/bhtom/bhtom/bhtom-env/lib/python3.6/site-packages/django_filters/filterset.py", line 237, in qs
    qs = self.filter_queryset(qs)
  File "/home/bhtom/bhtom/bhtom-env/lib/python3.6/site-packages/django_filters/filterset.py", line 224, in filter_queryset
    queryset = self.filters[name].filter(queryset, value)
  File "/home/bhtom/bhtom/bhtom-env/lib/python3.6/site-packages/django_filters/filters.py", line 765, in __call__
    return self.method(qs, self.f.field_name, value)
  File "/home/bhtom/bhtom/bhtom-env/lib/python3.6/site-packages/tom_targets/filters.py", line 28, in filter_number
    targetextra__key=name, targetextra__float_value__gte=value.start, targetextra__float_value__lte=value.stop
  File "/home/bhtom/bhtom/bhtom-env/lib/python3.6/site-packages/django/db/models/query.py", line 892, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/home/bhtom/bhtom/bhtom-env/lib/python3.6/site-packages/django/db/models/query.py", line 910, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/home/bhtom/bhtom/bhtom-env/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1290, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/bhtom/bhtom/bhtom-env/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1318, in _add_q
    split_subq=split_subq, simple_col=simple_col,
  File "/home/bhtom/bhtom/bhtom-env/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1251, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/home/bhtom/bhtom/bhtom-env/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1121, in build_lookup
    raise ValueError("Cannot use None as a query value")
ValueError: Cannot use None as a query value

**Comment by majkelx** [comment]
A czy ktoś wie czy są w tym URL pola customowe dla BHTom (nie standardowego TOMa)?

Może ktoś z nas dodawał i złe obsługuje puste wartosci dla filtra?
